// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ooklajermcompfanffwl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9va2xhamVybWNvbXBmYW5mZndsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NjE2OTEsImV4cCI6MjA3MDEzNzY5MX0.wpxbK33ikYQ0EWgUp-A0ee30GPQIgGKOp5LyTSvKMlI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});